### ISSUE TITLE
Issue - Cast only returning 250 results

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#26]
This is a new issue, just noticed this today.  If a movie has 250+ credits, it caps out at 250.  Is there anything that can be done with this?

Example - https://www.imdb.com/title/tt8667828/fullcredits

**Comment by duck7000** [comment]
Mm now you mentioned it i see it too.

I'm not sure this can be fixed, it could be the same as with episodes

Tboothman did made a different GraphQL function to get data that is paginated but i'm not sure if this will work or fix this issue.
I will investigate this

**Comment by GeorgeFive** [comment]
Thanks.... definitely a big issue here, I think.

**Comment by duck7000** [comment]
Well big or not if there is a limit and i cannot overcome it somehow we have to live with it i guess.

I will try

**Comment by duck7000** [comment]
So far i have tried with the other Tboothman method and it seems sofar that i can get all cast with this method
I tried the walking dead and it returns an array with 990 elements so that is promising.

A lot of the cast method has to be changed so we are not out of the woods jet

If this goes all well i might tackle the 250 limit on episode as well but no promises! Episodes is a less of a problem than cast

**Comment by duck7000** [comment]
I think i fixed that 250 results limit.
I uploaded the fixed methods so check it out and let me know if it is indeed fixed.

**Comment by GeorgeFive** [comment]
Fixed!

**Comment by duck7000** [comment]
Great!

Thanks for testing
