### ISSUE TITLE
Request: Goofs

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbphp6#8]
Hi, Would it be possible to implement the former goofs() method in Title class? Thanks!

**Comment by duck7000** [comment]
Mm i started this version to be independent and only what i absolutely needed but it is growing quickly.
Is this something you definitely want or is it "nice to have"?

I'm asking because i don't want to end up whit a full blown version that is the same as imdbphp.

And i have already added some methods which i never will be using

I hope you understand that

**Comment by jcvignoli** [comment]
You asked me what functions do I need, goofs is one of the mehtods I do need :)
I understand you may not want to implement it. I suppose your approach (graphQL) is much more stable than the previous one (regex on pages), and hope it will require less maintenance.
I'd perfectly understand should you not want implement it. I will fork your version :)

**Comment by duck7000** [comment]
I'm not that worried about maintenance, imdb can change their API but i think that would not happen that often as i looked at the release notes

I do worry about more and more methods that i don't use /ever going to use. But on the other side i do understand that if other users are going to use my version their needs may change. That's why i asked what you absolutely need.

Are there more methods you need?

As always, i'll think about it :)

**Comment by jcvignoli** [comment]
I understand.
So far, there is no further method I need, but I'm in the process of checking all dead methods. Seems that's ok so far :)

**Comment by duck7000** [comment]
Does goofs in or exclude spoilers, imdbphp did exclude?
And do you want all goof categories or a particular one?

**Comment by duck7000** [comment]
There are more users that asked for methods, which i added, but i did not notice that this request came from a different user..
Apologies

I'll see what i can do to make it work

**Comment by duck7000** [comment]
i added back goofs method

check it out

**Comment by jcvignoli** [comment]
Works perfectly, thanks so much!

**Comment by duck7000** [comment]
Thanks
I had to add a sort method to sort the output array, through GraphQL i can't get them sorted

I added crazyCredit as well, maybe for future use
